/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 21 02:58:30 GMT 2022
 */

package com.ctc.wstx.sax;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ctc.wstx.sax.WrappedSaxException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.xml.sax.SAXException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WrappedSaxException_ESTest extends WrappedSaxException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SAXException sAXException0 = new SAXException("com.ctc.wstx.sax.WrappedSaxException");
      WrappedSaxException wrappedSaxException0 = new WrappedSaxException(sAXException0);
      String string0 = wrappedSaxException0.toString();
      assertEquals("org.xml.sax.SAXException: com.ctc.wstx.sax.WrappedSaxException", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SAXException sAXException0 = new SAXException("com.ctc.wstx.sax.WrappedSaxException");
      WrappedSaxException wrappedSaxException0 = new WrappedSaxException(sAXException0);
      SAXException sAXException1 = wrappedSaxException0.getSaxException();
      assertSame(sAXException0, sAXException1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SAXException sAXException0 = new SAXException("com.ctc.wstx.sax.WrappedSaxException");
      SAXException sAXException1 = new SAXException(sAXException0);
      sAXException0.initCause(sAXException1);
      WrappedSaxException wrappedSaxException0 = new WrappedSaxException(sAXException1);
      // Undeclared exception!
      try { 
        wrappedSaxException0.toString();
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WrappedSaxException wrappedSaxException0 = new WrappedSaxException((SAXException) null);
      SAXException sAXException0 = wrappedSaxException0.getSaxException();
      assertNull(sAXException0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WrappedSaxException wrappedSaxException0 = new WrappedSaxException((SAXException) null);
      // Undeclared exception!
      try { 
        wrappedSaxException0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ctc.wstx.sax.WrappedSaxException", e);
      }
  }
}
