/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 25 07:48:06 GMT 2022
 */

package net.segoia.commons.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.segoia.commons.exceptions.ContextAwareException;
import net.segoia.commons.exceptions.ExceptionContext;
import net.segoia.commons.exceptions.ExceptionHandler;
import net.segoia.commons.exceptions.ExceptionHandlerConfiguration;
import net.segoia.commons.exceptions.ExceptionHandlerWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ExtendedExceptionHandler_ESTest extends ExtendedExceptionHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExceptionHandlerWrapper<Object> exceptionHandlerWrapper0 = new ExceptionHandlerWrapper<Object>();
      exceptionHandlerWrapper0.getWrappedExceptionHandler();
      ExceptionHandlerWrapper<Integer> exceptionHandlerWrapper1 = new ExceptionHandlerWrapper<Integer>();
      exceptionHandlerWrapper1.setWrappedExceptionHandler(exceptionHandlerWrapper1);
      ContextAwareException contextAwareException0 = new ContextAwareException("net.segoia.util.data.NameValueContext");
      // Undeclared exception!
      try { 
        exceptionHandlerWrapper1.handle(contextAwareException0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ExceptionHandlerWrapper<Integer> exceptionHandlerWrapper0 = new ExceptionHandlerWrapper<Integer>();
      // Undeclared exception!
      try { 
        exceptionHandlerWrapper0.handle((ContextAwareException) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.segoia.commons.exceptions.ExceptionHandlerWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ExceptionHandlerWrapper<Object> exceptionHandlerWrapper0 = new ExceptionHandlerWrapper<Object>();
      String string0 = "}xjq4qC8`zbbaE/i";
      ExceptionContext exceptionContext0 = new ExceptionContext();
      ContextAwareException contextAwareException0 = new ContextAwareException("}xjq4qC8`zbbaE/i", exceptionContext0);
      contextAwareException0.toString();
      contextAwareException0.getMessage();
      // Undeclared exception!
      try { 
        exceptionHandlerWrapper0.handle(contextAwareException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.segoia.commons.exceptions.ExceptionHandlerWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ExceptionHandlerWrapper<Object> exceptionHandlerWrapper0 = new ExceptionHandlerWrapper<Object>();
      ExceptionHandlerWrapper<Integer> exceptionHandlerWrapper1 = new ExceptionHandlerWrapper<Integer>();
      ExceptionHandlerConfiguration exceptionHandlerConfiguration0 = exceptionHandlerWrapper1.getConfig();
      exceptionHandlerWrapper0.setConfig(exceptionHandlerConfiguration0);
      exceptionHandlerWrapper0.getWrappedExceptionHandler();
      exceptionHandlerWrapper0.setWrappedExceptionHandler((ExceptionHandler<Object>) null);
      ExceptionHandlerWrapper<Integer> exceptionHandlerWrapper2 = new ExceptionHandlerWrapper<Integer>();
      ContextAwareException contextAwareException0 = new ContextAwareException("", (ExceptionContext) null);
      // Undeclared exception!
      try { 
        contextAwareException0.addExceptionParameter("net.segoia.commons.exceptions.ExtendedExceptionHandler", (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.segoia.commons.exceptions.ContextAwareException", e);
      }
  }
}
